# This Actions file will update all plots each Wednesday morning
name: updateplots
on:
  #schedule:
  #  - cron: '00 13 * * 3'
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    env:
      FRED_KEY: ${{ secrets.FRED_KEY }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - name: Run R script
        run: Rscript 'R/C02.R'
      - name: Commit results
        run: |
          git config --global user.email "trevor.tombe@gmail.com"
          git config --global user.name "Trevor Tombe"
          git add 'Figures/*.*' 'Data/*.*'
          git commit -m "Update All Plots" || echo "No changes to commit"
          git push origin || echo "No changes to commit"
