# This Actions file will update all plots each Wednesday morning
name: updatefigures
on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    env:
      FRED_KEY: ${{ secrets.FRED_KEY }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - name: Run R script 2
        run: Rscript 'R/C02.R'
      - name: Run R script 7
        run: Rscript 'R/C07.R'
      - name: Commit results
        run: |
          git config --global user.email "trevor.tombe@gmail.com"
          git config --global user.name "Trevor Tombe"
          git add 'Figures/*.*' 'Data/*.*'
          git commit -m "Update All Figures" || echo "No changes to commit"
          git push origin || echo "No changes to commit"
